.TH dtestx 1 "February 23, 2007" "uDAPL 1.2" "USER COMMANDS"
.SH NAME
dtestx \- simple IB extensions test utility.
.SH SYNOPSIS
.B dtestx
.SH DESCRIPTION
.PP
This program does not currently have any documentation. This manpage
is a placeholder.
.SH SEE ALSO
.BR dapltest(1)
.BR dtest(1)
.SH AUTHORS
Guy Coates < gmpc@sanger.ac.uk >
