
LIBDFV_DIR = libdfv
LIBCMI_DIR = libcmi
LIBIPS_DIR = libips
LIBIDT_DIR = libidt
SYSLK_DIR = syslk
SYSAGT_DIR = sysagt

all:
	@if [ -d $(LIBDFV_DIR) ]; then cd $(LIBDFV_DIR) && $(MAKE) $@; fi
	@if [ -d $(LIBCMI_DIR) ]; then cd $(LIBCMI_DIR) && $(MAKE) $@; fi
	@if [ -d $(LIBIPS_DIR) ]; then cd $(LIBIPS_DIR) && $(MAKE) $@; fi
	@if [ -d $(LIBIDT_DIR) ]; then cd $(LIBIDT_DIR) && $(MAKE) $@; fi
	@if [ -d $(SYSLK_DIR) ]; then cd $(SYSLK_DIR) && $(MAKE) $@; fi
	@if [ -d $(SYSAGT_DIR) ]; then cd $(SYSAGT_DIR) && $(MAKE) $@; fi

clean:
	@if [ -d $(LIBDFV_DIR) ]; then cd $(LIBDFV_DIR) && $(MAKE) $@; fi
	@if [ -d $(LIBCMI_DIR) ]; then cd $(LIBCMI_DIR) && $(MAKE) $@; fi
	@if [ -d $(LIBIPS_DIR) ]; then cd $(LIBIPS_DIR) && $(MAKE) $@; fi
	@if [ -d $(LIBIDT_DIR) ]; then cd $(LIBIDT_DIR) && $(MAKE) $@; fi
	@if [ -d $(SYSLK_DIR) ]; then cd $(SYSLK_DIR) && $(MAKE) $@; fi
	@if [ -d $(SYSAGT_DIR) ]; then cd $(SYSAGT_DIR) && $(MAKE) $@; fi

