
#line 3 "osm_qos_parser_l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[582] =
    {   0,
        0,    0,   85,   83,    3,    4,   83,   83,   81,   80,
       78,   77,   77,   79,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,   83,   83,   83,   83,   83,   83,
       83,   83,   83,   83,    3,    2,    0,   82,    0,    1,
       77,    0,    0,    0,   57,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   76,   60,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,   45,    0,    0,   39,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   69,    0,    0,
        0,   67,   59,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   45,    0,   39,    0,   34,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   71,    0,
        0,   69,    0,    0,    0,   67,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   40,    0,    0,    0,
       33,    0,    0,    0,    0,    0,   54,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   34,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   74,    0,    0,
       71,    0,   56,    0,    0,   58,    0,    0,    0,    0,
        0,    0,   40,    0,   35,    0,   33,    0,    0,    0,
        0,   54,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   74,    0,    0,    0,    0,    0,    0,   43,
        0,    0,    0,    0,    0,   35,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   51,    0,    0,    0,    0,    0,
       63,    0,    0,    0,    0,   61,    0,    0,    0,    0,

        0,    0,    0,   43,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    5,    0,    0,    0,    0,   51,    0,    0,    0,
        0,    0,    0,    0,    0,   61,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       23,    0,   11,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   75,    0,    0,    0,    0,
        0,    0,   41,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   46,    0,   32,    0,    0,   31,    0,   49,

        9,    0,   29,    0,   30,    0,   50,    0,   21,    0,
        0,    0,    0,    0,    0,    0,    0,   37,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   41,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   46,
       32,    0,   31,   49,    7,   29,   30,   50,    0,    0,
        0,   47,    0,   53,   19,    0,    0,    0,   36,   37,
       15,    0,    0,    0,    0,    0,    0,   70,   68,    0,
        0,   42,    0,   52,    0,    0,    0,    0,    6,    0,
        0,    0,    0,    0,   48,    0,    0,   47,   53,    0,
       44,   17,    0,   36,   13,    0,    0,    0,    0,   72,

        0,   42,   52,    0,   24,    0,   12,    0,    0,    0,
        0,   48,    0,    0,   44,    0,   62,    0,    0,    0,
        0,   10,   22,    0,    0,    0,    0,    0,    0,   27,
        0,   38,    0,    0,    0,    0,    8,    0,   20,    0,
       16,    0,    0,   55,   25,   38,    0,    0,    0,    0,
        0,   18,   14,   55,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   28,    0,    0,    0,    0,   26,   65,
        0,   64,   73,    0,    0,    0,    0,    0,    0,   66,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    1,    7,    8,    1,    1,    9,   10,   11,
       10,   10,   10,   10,   10,   10,   10,   12,    1,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
        1,   19,   20,    1,    1,   21,    1,   22,   23,   24,
        1,   25,   26,   27,   28,    1,   29,   30,   31,    1,
        1,    1,    1,    1,    1,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    1,   41,   42,   43,   44,
       45,   46,   47,   48,   49,   50,   51,   52,   53,   30,
       54,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[55] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    1,    2,    2,    2,    2,    2,    2,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    2,    2,    2,    2,    2,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[585] =
    {   0,
        0,    0,  790,  791,   53,  791,  785,  785,  791,  791,
      791,   48,   51,  791,   42,   53,   51,   43,   56,   77,
       54,   54,  743,  738,  737,  734,   38,   63,  738,   84,
      115,  737,  732,  738,   71,  791,  775,  791,  775,  791,
       71,    0,   76,   68,  791,   87,   88,   92,   77,   86,
       93,   94,   96,  101,  729,  109,  741,  730,  729,  722,
      729,  736,  104,  734,  721,  719,  717,  113,  154,  715,
      133,  729,  115,    0,  791,  141,  140,  129,  134,  168,
      135,  169,  146,  171,  140,  719,  713,  754,  718,  709,
      751,  722,  721,  715,  705,  715,  699,  702,  743,  714,

      697,  172,  696,  745,  698,  175,  743,  177,  705,  695,
      184,  186,  164,  179,  192,  193,  194,  740,  180,  196,
      199,  739,  791,  200,  204,  194,  691,  699,  171,  209,
      692,  695,  212,  728,  699,  694,  725,  217,  724,  188,
      723,  690,  687,  726,  693,  724,  231,  723,  684,  690,
      211,  681,  189,  689,  205,  239,  246,  225,  718,  236,
      674,  716,  217,  242,  672,  714,  247,  683,  231,  665,
      669,  667,  666,  668,  667,  250,  706,  254,  667,  257,
      704,  655,  654,  653,  669,  261,  699,  230,  658,  663,
      666,  661,  654,  653,  660,  685,  656,  689,  652,  681,

      652,  639,  635,  637,  228,  265,  262,  682,  273,  638,
      680,  633,  791,  632,  631,  791,  277,  646,  629,  627,
      664,  642,  671,  274,  670,  628,  668,  615,  660,  627,
      626,  663,  232,  632,  631,  610,  611,  610,  613,  618,
      621,  241,  282,  617,  253,  601,  602,  605,  614,  294,
      279,  610,  648,  601,  598,  597,  608,  297,  250,  643,
      594,  593,  634,  589,  592,  637,  598,  591,  594,  590,
      584,  588,  592,  588,  581,  593,  594,  576,  577,  582,
      616,  589,  590,  299,  619,  612,  579,  573,  583,  584,
      791,  575,  580,  577,  302,  610,  575,  560,  601,  600,

      571,  558,  560,  602,  563,  594,  273,  559,  567,  549,
      562,  557,  552,  546,  543,  558,  556,  542,  548,  550,
      542,  791,  547,  546,  540,  551,  581,  540,  543,  527,
      534,  545,  543,  540,  525,  572,  519,  564,  527,  526,
      519,  523,  305,  522,  528,  529,  532,  527,  520,  553,
      552,  308,  311,  522,  316,  319,  512,  324,  325,  327,
      285,  549,  791,  506,  520,  508,  511,  512,  512,  328,
      504,  507,  512,  539,  538,  791,  501,  493,  492,  534,
      498,  330,  538,  495,  490,  485,  486,  485,  488,  294,
      296,  336,  531,  339,  530,  495,  345,  528,  347,  527,

      479,  348,  525,  350,  524,  351,  523,  480,  791,  475,
      352,  353,  486,  485,  477,  354,  356,  517,  482,  481,
      508,  321,  469,  463,  470,  469,  465,  367,  508,  368,
      464,  472,  473,  455,  456,  470,  471,  468,  469,  498,
      497,  370,  496,  495,  791,  494,  493,  492,  461,  441,
      371,  489,  372,  488,  791,  373,  449,  374,  486,  485,
      791,  437,  445,  439,  451,  437,  438,  791,  791,  435,
      375,  477,  376,  476,  426,  434,  436,  428,  791,  428,
      439,  426,  437,  379,  467,  425,  425,  464,  463,  387,
      462,  791,  413,  460,  791,  426,  412,  411,  410,  791,

      409,  454,  453,  408,  404,  444,  791,  405,  408,  403,
      406,  445,  410,  409,  442,  388,  791,  393,  404,  391,
      390,  390,  791,  390,  401,  400,  399,  398,  390,  384,
      391,  430,  423,  394,  421,  420,  791,  376,  791,  372,
      791,  371,  392,  417,  791,  416,  379,  366,  377,  376,
      371,  791,  791,  410,  360,  402,  358,  357,  371,  366,
      359,  361,  358,  348,  361,  350,  326,  300,  791,  791,
      285,  791,  791,  262,  297,  260,  159,   70,   42,  791,
      791,  422,  424,   63
    } ;

static yyconst flex_int16_t yy_def[585] =
    {   0,
      581,    1,  581,  581,  581,  581,  582,  583,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  582,  581,  583,  581,
      581,  584,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  584,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
        0,  581,  581,  581
    } ;

static yyconst flex_int16_t yy_nxt[846] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       13,   14,   15,    4,   16,   17,    4,    4,    4,   18,
        4,    4,    4,    4,   19,   20,    4,    4,    4,    4,
        4,   21,    4,   16,   22,   23,   24,   25,    4,   18,
        4,    4,   26,   27,    4,   28,   29,   30,   31,   32,
       33,   34,    4,    4,   35,   36,   41,   41,   41,   41,
       41,   41,   43,   44,   74,   45,   47,   46,   48,   61,
       46,   49,   35,   36,   43,   44,  580,   42,   50,   41,
       41,   41,   62,   43,   45,   44,   46,   55,   47,   56,
       49,   48,   51,   52,   63,   43,   75,   44,   76,   49,

       50,   53,   80,   64,   77,   54,   50,   65,   79,  579,
       78,   51,   52,   81,   83,   67,   82,   75,   49,   84,
       85,   76,  109,   77,   53,   80,   77,   79,   50,   54,
       51,   52,   78,   83,  106,   83,   81,   94,   82,   53,
       85,   84,  111,   54,  107,   77,  110,  112,  114,   51,
       68,   95,  113,   96,   83,  102,   69,   87,  115,   70,
      101,  119,   53,  123,  103,  104,  126,   54,  114,  116,
      120,  113,  124,  102,  117,  121,  106,  125,  147,  118,
      122,  115,  123,  104,  119,  111,  107,  151,  148,  126,
      112,  155,  156,  157,  116,  160,  163,  120,  158,  117,

      164,  124,  121,  159,  118,  167,  125,  122,  169,  578,
      176,  156,  151,  180,  155,  163,  172,  173,  186,  174,
      177,  189,  175,  181,  202,  205,  209,  169,  187,  190,
      191,  152,  147,  203,  153,  154,  192,  160,  193,  161,
      206,  213,  148,  164,  165,  207,  205,  157,  167,  216,
      208,  176,  158,  168,  250,  224,  152,  159,  180,  153,
      154,  177,  186,  251,  213,  225,  206,  233,  181,  216,
      210,  207,  187,  234,  209,  224,  208,  250,  258,  272,
      251,  161,  273,  284,  259,  225,  302,  165,  260,  282,
      283,  287,  408,  285,  288,  295,  168,  577,  258,  303,

      284,  289,  290,  295,  576,  296,  382,  252,  260,  392,
      285,  575,  394,  296,  346,  347,  383,  397,  210,  393,
      399,  348,  395,  349,  252,  402,  404,  398,  406,  417,
      400,  382,  574,  409,  573,  403,  405,  392,  407,  418,
      394,  383,  436,  437,  438,  439,  397,  393,  399,  402,
      395,  404,  406,  451,  453,  458,  398,  417,  400,  403,
      572,  405,  407,  452,  454,  459,  464,  418,  471,  473,
      465,  484,  451,  453,  490,  458,  471,  473,  472,  474,
      484,  485,  452,  454,  491,  459,  472,  474,  490,  531,
      485,  543,  531,  543,  571,  570,  569,  568,  491,  532,

      567,  544,  532,  544,  566,  565,  564,  563,  562,  561,
      560,  554,  559,  558,  557,  556,  555,  546,  554,  553,
      552,  492,   37,   37,   39,   39,  551,  550,  549,  548,
      547,  546,  545,  542,  541,  540,  539,  538,  537,  536,
      535,  534,  533,  515,  530,  529,  512,  528,  527,  526,
      525,  524,  523,  522,  503,  502,  521,  520,  519,  518,
      517,  494,  516,  515,  489,  488,  514,  513,  512,  511,
      510,  509,  508,  507,  506,  505,  504,  503,  502,  501,
      500,  499,  498,  497,  496,  495,  460,  494,  493,  489,
      488,  487,  486,  448,  447,  446,  444,  443,  441,  440,

      483,  482,  481,  480,  479,  478,  477,  476,  475,  429,
      470,  469,  468,  467,  466,  463,  462,  461,  460,  457,
      456,  455,  450,  449,  448,  447,  446,  445,  444,  443,
      442,  441,  440,  435,  434,  433,  432,  431,  430,  429,
      428,  427,  426,  425,  424,  423,  422,  421,  420,  419,
      416,  415,  414,  413,  412,  411,  410,  401,  396,  391,
      390,  389,  388,  387,  386,  385,  384,  381,  380,  379,
      378,  377,  376,  336,  375,  374,  373,  372,  371,  370,
      369,  368,  327,  367,  366,  365,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,

      350,  345,  344,  304,  343,  342,  341,  340,  339,  338,
      337,  336,  335,  334,  333,  332,  331,  330,  329,  328,
      327,  326,  325,  324,  323,  322,  321,  320,  319,  318,
      317,  316,  315,  314,  313,  312,  311,  310,  266,  309,
      308,  307,  306,  305,  304,  301,  300,  299,  298,  253,
      297,  294,  293,  292,  291,  286,  281,  280,  279,  278,
      277,  276,  275,  274,  232,  271,  270,  269,  268,  227,
      267,  266,  223,  265,  264,  263,  262,  261,  257,  256,
      255,  211,  254,  253,  249,  248,  247,  246,  245,  244,
      198,  243,  242,  241,  240,  239,  238,  237,  236,  235,

      232,  231,  230,  229,  228,  227,  226,  223,  222,  221,
      220,  219,  218,  217,  215,  166,  214,  162,  212,  211,
      204,  201,  200,  199,  198,  146,  197,  144,  196,  195,
      194,  188,  185,  184,  183,  182,  179,  178,  171,  170,
      166,  162,  150,  149,  146,  145,  144,  143,  142,  141,
      140,  139,  138,  137,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  127,  108,  105,  100,   99,   98,   97,
       93,   92,   91,   90,   89,   88,   86,   40,   38,   73,
       72,   71,   66,   60,   59,   58,   57,   40,   38,  581,
        3,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581
    } ;

static yyconst flex_int16_t yy_chk[846] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,   12,   12,   12,   13,
       13,   13,   15,   15,  584,   16,   18,   17,   18,   27,
       22,   19,   35,   35,   21,   21,  579,   12,   19,   41,
       41,   41,   27,   15,   16,   15,   17,   21,   18,   22,
       19,   18,   20,   20,   28,   21,   43,   21,   44,   30,

       19,   20,   49,   28,   46,   20,   30,   28,   48,  578,
       47,   20,   20,   50,   52,   30,   51,   43,   30,   53,
       54,   44,   73,   46,   20,   49,   56,   48,   30,   20,
       31,   31,   47,   68,   71,   52,   50,   63,   51,   31,
       54,   53,   76,   31,   71,   56,   73,   76,   78,   31,
       31,   63,   77,   63,   68,   69,   31,   56,   79,   31,
       68,   81,   31,   83,   69,   69,   85,   31,   78,   80,
       82,   77,   84,  102,   80,   82,  106,   84,  108,   80,
       82,   79,   83,  102,   81,  111,  106,  112,  108,   85,
      111,  113,  114,  115,  116,  117,  119,  120,  115,  116,

      121,  124,  120,  115,  116,  125,  124,  120,  126,  577,
      130,  114,  151,  133,  113,  119,  129,  129,  138,  129,
      130,  140,  129,  133,  153,  155,  158,  126,  138,  140,
      140,  112,  147,  153,  112,  112,  140,  160,  140,  117,
      156,  163,  147,  164,  121,  156,  155,  157,  167,  169,
      156,  176,  157,  125,  205,  178,  151,  157,  180,  151,
      151,  176,  186,  207,  163,  178,  206,  188,  180,  169,
      158,  206,  186,  188,  209,  224,  206,  205,  217,  233,
      251,  160,  233,  243,  217,  224,  259,  164,  217,  242,
      242,  245,  361,  243,  245,  250,  167,  576,  258,  259,

      284,  245,  245,  295,  575,  250,  343,  207,  258,  352,
      284,  574,  353,  295,  307,  307,  343,  355,  209,  352,
      356,  307,  353,  307,  251,  358,  359,  355,  360,  370,
      356,  382,  571,  361,  568,  358,  359,  392,  360,  370,
      394,  382,  390,  390,  391,  391,  397,  392,  399,  402,
      394,  404,  406,  411,  412,  416,  397,  417,  399,  402,
      567,  404,  406,  411,  412,  416,  422,  417,  428,  430,
      422,  442,  451,  453,  456,  458,  471,  473,  428,  430,
      484,  442,  451,  453,  456,  458,  471,  473,  490,  516,
      484,  529,  531,  543,  566,  565,  564,  563,  490,  516,

      562,  529,  531,  543,  561,  560,  559,  558,  557,  556,
      555,  554,  551,  550,  549,  548,  547,  546,  544,  542,
      540,  456,  582,  582,  583,  583,  538,  536,  535,  534,
      533,  532,  530,  528,  527,  526,  525,  524,  522,  521,
      520,  519,  518,  515,  514,  513,  512,  511,  510,  509,
      508,  506,  505,  504,  503,  502,  501,  499,  498,  497,
      496,  494,  493,  491,  489,  488,  487,  486,  485,  483,
      482,  481,  480,  478,  477,  476,  475,  474,  472,  470,
      467,  466,  465,  464,  463,  462,  460,  459,  457,  454,
      452,  450,  449,  448,  447,  446,  444,  443,  441,  440,

      439,  438,  437,  436,  435,  434,  433,  432,  431,  429,
      427,  426,  425,  424,  423,  421,  420,  419,  418,  415,
      414,  413,  410,  408,  407,  405,  403,  401,  400,  398,
      396,  395,  393,  389,  388,  387,  386,  385,  384,  383,
      381,  380,  379,  378,  377,  375,  374,  373,  372,  371,
      369,  368,  367,  366,  365,  364,  362,  357,  354,  351,
      350,  349,  348,  347,  346,  345,  344,  342,  341,  340,
      339,  338,  337,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,  326,  325,  324,  323,  321,  320,  319,
      318,  317,  316,  315,  314,  313,  312,  311,  310,  309,

      308,  306,  305,  304,  303,  302,  301,  300,  299,  298,
      297,  296,  294,  293,  292,  290,  289,  288,  287,  286,
      285,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  257,  256,  255,  254,  253,
      252,  249,  248,  247,  246,  244,  241,  240,  239,  238,
      237,  236,  235,  234,  232,  231,  230,  229,  228,  227,
      226,  225,  223,  222,  221,  220,  219,  218,  215,  214,
      212,  211,  210,  208,  204,  203,  202,  201,  200,  199,
      198,  197,  196,  195,  194,  193,  192,  191,  190,  189,

      187,  185,  184,  183,  182,  181,  179,  177,  175,  174,
      173,  172,  171,  170,  168,  166,  165,  162,  161,  159,
      154,  152,  150,  149,  148,  146,  145,  144,  143,  142,
      141,  139,  137,  136,  135,  134,  132,  131,  128,  127,
      122,  118,  110,  109,  107,  105,  104,  103,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   92,   91,   90,
       89,   88,   87,   86,   72,   70,   67,   66,   65,   64,
       62,   61,   60,   59,   58,   57,   55,   39,   37,   34,
       33,   32,   29,   26,   25,   24,   23,    8,    7,    3,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,

      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581,  581,  581,  581,  581,  581,
      581,  581,  581,  581,  581
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "osm_qos_parser_l.l"
#line 2 "osm_qos_parser_l.l"
/*
 * Copyright (c) 2004-2006 Voltaire, Inc. All rights reserved.
 * Copyright (c) 2002-2008 Mellanox Technologies LTD. All rights reserved.
 * Copyright (c) 1996-2003 Intel Corporation. All rights reserved.
 *
 * This software is available to you under a choice of one of two
 * licenses.  You may choose to be licensed under the terms of the GNU
 * General Public License (GPL) Version 2, available from the file
 * COPYING in the main directory of this source tree, or the
 * OpenIB.org BSD license below:
 *
 *     Redistribution and use in source and binary forms, with or
 *     without modification, are permitted provided that the following
 *     conditions are met:
 *
 *      - Redistributions of source code must retain the above
 *        copyright notice, this list of conditions and the following
 *        disclaimer.
 *
 *      - Redistributions in binary form must reproduce the above
 *        copyright notice, this list of conditions and the following
 *        disclaimer in the documentation and/or other materials
 *        provided with the distribution.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/*
 * Abstract:
 *    Lexer of OSM QoS parser.
 *
 * Environment:
 *    Linux User Mode
 *
 * Author:
 *    Yevgeny Kliteynik, Mellanox
 */

#include <opensm/osm_qos_policy.h>
#include "osm_qos_parser_y.h"

#define HANDLE_IF_IN_DESCRIPTION   if (in_description) { yylval = strdup(yytext); return TK_TEXT; }

#define SAVE_POS save_pos()
static void save_pos();

extern int column_num;
extern int line_num;
extern FILE * yyin;
extern YYSTYPE yylval;

boolean_t in_description = FALSE;
boolean_t in_list_of_hex_num_ranges = FALSE;
boolean_t in_node_type = FALSE;
boolean_t in_list_of_numbers = FALSE;
boolean_t in_list_of_strings = FALSE;
boolean_t in_list_of_num_pairs = FALSE;
boolean_t in_asterisk_or_list_of_numbers = FALSE;
boolean_t in_list_of_num_ranges = FALSE;
boolean_t in_single_string = FALSE;
boolean_t in_single_number = FALSE;

static void reset_new_line_flags();
#define RESET_NEW_LINE_FLAGS reset_new_line_flags()

#define START_USE            {in_description = TRUE;}     /* list of strings including whitespace (description) */
#define START_PORT_GUID      {in_list_of_hex_num_ranges = TRUE;} /* comma-separated list of hex num ranges */
#define START_PORT_NAME      {in_list_of_strings = TRUE;} /* comma-separated list of following strings: ../../.. */
#define START_PARTITION      {in_single_string = TRUE;}   /* single string w/o whitespaces (partition name) */
#define START_NAME           {in_single_string = TRUE;}   /* single string w/o whitespaces (port group name) */
#define START_QOS_LEVEL_NAME {in_single_string = TRUE;}   /* single string w/o whitespaces (qos level name in match rule) */

#define START_NODE_TYPE     {in_node_type = TRUE;}       /* comma-separated list of node types (ROUTER,CA,...) */
#define START_SL2VL_TABLE   {in_list_of_numbers = TRUE;} /* comma-separated list of hex or dec numbers */

#define START_GROUP         {in_list_of_strings = TRUE;} /* list of strings w/o whitespaces (group names) */
#define START_ACROSS        {in_list_of_strings = TRUE;} /* list of strings w/o whitespaces (group names) */
#define START_ACROSS_TO     {in_list_of_strings = TRUE;} /* list of strings w/o whitespaces (group names) */
#define START_ACROSS_FROM   {in_list_of_strings = TRUE;} /* list of strings w/o whitespaces (group names) */
#define START_SOURCE        {in_list_of_strings = TRUE;} /* list of strings w/o whitespaces (group names) */
#define START_DESTINATION   {in_list_of_strings = TRUE;} /* list of strings w/o whitespaces (group names) */

#define START_VLARB_HIGH    {in_list_of_num_pairs = TRUE;} /* comma-separated list of hex or dec num pairs: "num1:num2" */
#define START_VLARB_LOW     {in_list_of_num_pairs = TRUE;} /* comma-separated list of hex or dec num pairs: "num1:num2" */

#define START_TO            {in_asterisk_or_list_of_numbers = TRUE;} /* (asterisk) or (comma-separated list of hex or dec numbers) */
#define START_FROM          {in_asterisk_or_list_of_numbers = TRUE;} /* (asterisk) or (comma-separated list of hex or dec numbers) */

#define START_PATH_BITS     {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_QOS_CLASS     {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_SERVICE_ID    {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_PKEY          {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */

#define START_SL               {in_single_number = TRUE;}   /* single number */
#define START_VLARB_HIGH_LIMIT {in_single_number = TRUE;}   /* single number */
#define START_MTU_LIMIT        {in_single_number = TRUE;}   /* single number */
#define START_RATE_LIMIT       {in_single_number = TRUE;}   /* single number */
#define START_PACKET_LIFE      {in_single_number = TRUE;}   /* single number */

#define START_ULP_DEFAULT       {in_single_number = TRUE;}      /* single number */
#define START_ULP_ANY           {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_ULP_SDP_DEFAULT   {in_single_number = TRUE;}      /* single number */
#define START_ULP_SDP_PORT      {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_ULP_RDS_DEFAULT   {in_single_number = TRUE;}      /* single number */
#define START_ULP_RDS_PORT      {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_ULP_ISER_DEFAULT  {in_single_number = TRUE;}      /* single number */
#define START_ULP_ISER_PORT     {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_ULP_SRP_GUID      {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */
#define START_ULP_IPOIB_DEFAULT {in_single_number = TRUE;}      /* single number */
#define START_ULP_IPOIB_PKEY    {in_list_of_num_ranges = TRUE;} /* comma-separated list of hex or dec num ranges */


#define YY_NO_INPUT 1
#line 949 "osm_qos_parser_l.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		unsigned n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 203 "osm_qos_parser_l.l"



#line 1133 "osm_qos_parser_l.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 582 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 791 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 206 "osm_qos_parser_l.l"
{ SAVE_POS; RESET_NEW_LINE_FLAGS; } /* swallow comment */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 207 "osm_qos_parser_l.l"
{ SAVE_POS; RESET_NEW_LINE_FLAGS; } /* trailing blanks with new line */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 208 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 209 "osm_qos_parser_l.l"
{ SAVE_POS; RESET_NEW_LINE_FLAGS; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 211 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_ULPS_START; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 212 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_ULPS_END; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 214 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_PORT_GROUPS_START; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 215 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_PORT_GROUPS_END; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 216 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_PORT_GROUP_START; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 217 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_PORT_GROUP_END; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 219 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_SETUP_START; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 220 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_SETUP_END; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 221 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_VLARB_TABLES_START; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 222 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_VLARB_TABLES_END; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 223 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_VLARB_SCOPE_START; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 224 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_VLARB_SCOPE_END; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 226 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_SL2VL_TABLES_START; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 227 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_SL2VL_TABLES_END; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 228 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_SL2VL_SCOPE_START; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 229 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_SL2VL_SCOPE_END; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 231 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_LEVELS_START; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 232 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_LEVELS_END; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 233 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_LEVEL_START; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 234 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_LEVEL_END; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 236 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_MATCH_RULES_START; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 237 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_MATCH_RULES_END; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 238 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_MATCH_RULE_START; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 239 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; return TK_QOS_MATCH_RULE_END; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 241 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_PORT_GUID;    return TK_PORT_GUID;  }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 242 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_PORT_NAME;    return TK_PORT_NAME;  }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 243 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_PARTITION;    return TK_PARTITION;  }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 244 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_NODE_TYPE;    return TK_NODE_TYPE;  }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 245 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_NAME;         return TK_NAME;       }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 246 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_USE;          return TK_USE;        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 247 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_GROUP;        return TK_GROUP;      }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 248 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_VLARB_HIGH;   return TK_VLARB_HIGH; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 249 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_VLARB_LOW;    return TK_VLARB_LOW;  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 250 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_VLARB_HIGH_LIMIT; return TK_VLARB_HIGH_LIMIT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 251 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_TO;           return TK_TO;         }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 252 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_FROM;         return TK_FROM;       }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 253 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ACROSS_TO;    return TK_ACROSS_TO;  }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 254 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ACROSS_FROM;  return TK_ACROSS_FROM;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 255 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ACROSS;       return TK_ACROSS;     }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 256 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_SL2VL_TABLE;  return TK_SL2VL_TABLE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 257 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_SL;           return TK_SL;         }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 258 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_MTU_LIMIT;    return TK_MTU_LIMIT;  }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 259 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_RATE_LIMIT;   return TK_RATE_LIMIT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 260 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_PACKET_LIFE;  return TK_PACKET_LIFE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 261 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_PATH_BITS;    return TK_PATH_BITS;  }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 262 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_QOS_CLASS;    return TK_QOS_CLASS;  }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 263 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_SOURCE;       return TK_SOURCE;     }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 264 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_DESTINATION;  return TK_DESTINATION;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 265 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_SERVICE_ID;   return TK_SERVICE_ID; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 266 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_PKEY;         return TK_PKEY;       }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 267 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_QOS_LEVEL_NAME; return TK_QOS_LEVEL_NAME;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 269 "osm_qos_parser_l.l"
{ SAVE_POS; if (in_node_type) return TK_NODE_TYPE_ROUTER; yylval = strdup(yytext); return TK_TEXT; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 270 "osm_qos_parser_l.l"
{ SAVE_POS; if (in_node_type) return TK_NODE_TYPE_CA;     yylval = strdup(yytext); return TK_TEXT; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 271 "osm_qos_parser_l.l"
{ SAVE_POS; if (in_node_type) return TK_NODE_TYPE_SWITCH; yylval = strdup(yytext); return TK_TEXT; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 272 "osm_qos_parser_l.l"
{ SAVE_POS; if (in_node_type) return TK_NODE_TYPE_SELF;   yylval = strdup(yytext); return TK_TEXT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 273 "osm_qos_parser_l.l"
{ SAVE_POS; if (in_node_type) return TK_NODE_TYPE_ALL;    yylval = strdup(yytext); return TK_TEXT; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 275 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_DEFAULT; return TK_ULP_DEFAULT; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 276 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_ANY; return TK_ULP_ANY_SERVICE_ID; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 277 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_ANY; return TK_ULP_ANY_PKEY; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 278 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_ANY; return TK_ULP_ANY_TARGET_PORT_GUID; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 279 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_ANY; return TK_ULP_ANY_SOURCE_PORT_GUID; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 280 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_ANY; return TK_ULP_ANY_SOURCE_TARGET_PORT_GUID; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 282 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_SDP_DEFAULT; return TK_ULP_SDP_DEFAULT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 283 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_SDP_PORT; return TK_ULP_SDP_PORT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 285 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_RDS_DEFAULT; return TK_ULP_RDS_DEFAULT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 286 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_RDS_PORT; return TK_ULP_RDS_PORT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 288 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_SDP_DEFAULT; return TK_ULP_ISER_DEFAULT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 289 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_SDP_PORT; return TK_ULP_ISER_PORT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 291 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_SRP_GUID; return TK_ULP_SRP_GUID; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 293 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_IPOIB_DEFAULT; return TK_ULP_IPOIB_DEFAULT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 294 "osm_qos_parser_l.l"
{ SAVE_POS; HANDLE_IF_IN_DESCRIPTION; START_ULP_IPOIB_PKEY; return TK_ULP_IPOIB_PKEY; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 296 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        yylval = strdup(yytext);
                        if (in_description || in_list_of_strings || in_single_string)
                            return TK_TEXT;
                        return TK_NUMBER;
                    }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 304 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        yylval = strdup(yytext);
                        if (in_description || in_list_of_strings || in_single_string)
                            return TK_TEXT;
                        return TK_NUMBER;
                    }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 313 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        if (in_description || in_list_of_strings || in_single_string)
                        {
                            yylval = strdup(yytext);
                            return TK_TEXT;
                        }
                        return TK_DASH;
                    }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 323 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        if (in_description || in_list_of_strings || in_single_string)
                        {
                            yylval = strdup(yytext);
                            return TK_TEXT;
                        }
                        return TK_DOTDOT;
                    }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 333 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        if (in_description)
                        {
                            yylval = strdup(yytext);
                            return TK_TEXT;
                        }
                        return TK_COMMA;
                    }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 343 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        if (in_description || in_list_of_strings || in_single_string)
                        {
                            yylval = strdup(yytext);
                            return TK_TEXT;
                        }
                        return TK_ASTERISK;
                    }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 353 "osm_qos_parser_l.l"
{
                        SAVE_POS;
                        yylval = strdup(&yytext[1]);
                        yylval[strlen(yylval)-1] = '\0';
                        return TK_TEXT;
                    }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 360 "osm_qos_parser_l.l"
{ SAVE_POS; yylval = strdup(yytext); return TK_TEXT;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 362 "osm_qos_parser_l.l"
{
                        YY_NEW_FILE;
                        yyterminate();
                    }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 366 "osm_qos_parser_l.l"
ECHO;
	YY_BREAK
#line 1696 "osm_qos_parser_l.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 582 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 582 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 581);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 366 "osm_qos_parser_l.l"




/*********************************************
 *********************************************/

static void save_pos()
{
    int i;
    for (i = 0; i < yyleng; i++)
    {
        if (yytext[i] == '\n')
        {
            line_num ++;
            column_num = 1;
        }
        else
            column_num ++;
    }
}

/*********************************************
 *********************************************/

static void reset_new_line_flags()
{
    in_description = FALSE;
    in_list_of_hex_num_ranges = FALSE;
    in_node_type = FALSE;
    in_list_of_numbers = FALSE;
    in_list_of_strings = FALSE;
    in_list_of_num_pairs = FALSE;
    in_asterisk_or_list_of_numbers = FALSE;
    in_list_of_num_ranges = FALSE;
    in_single_string = FALSE;
    in_single_number = FALSE;
}

