#! /bin/bash

SCRIPTPATH=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd)

moddir=$1

modules=`find $moddir -name *.ko`

MODSECKEY=${MODULE_SIGN_PRIV_KEY}
MODPUBKEY=${MODULE_SIGN_PUB_KEY}

for mod in $modules
do
    dir=`dirname $mod`
    file=`basename $mod`

    ${SCRIPTPATH}/sign-file sha256 ${MODSECKEY} ${MODPUBKEY} ${dir}/${file}
    rm -f ${dir}/${file}.{sig,dig}
done

RANDOMMOD=$(find $moddir -type f -name '*.ko' | sort -R | tail -n 1)
if [ "~Module signature appended~" != "$(tail -c 28 $RANDOMMOD)" ]; then
	echo "*** Modules are unsigned! ***"
	exit 1
fi

exit 0
